FROM adoptopenjdk/openjdk11:alpine-jre
MAINTAINER lijo Joseph
COPY target/ApiGatewayService-0.0.1-SNAPSHOT.jar ApiGatewayService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ApiGatewayService-0.0.1-SNAPSHOT.jar"]