server:
  port: 8088
  
spring:
  application:
    name: flight-user-service
  
  datasource:
    url: jdbc:mysql://localhost:3307/flight_user_db?useSSL=false
    username: root
    password: root
  
jwt:
  secret: secretkey
  token:
    validity: 300000
#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans
  info:
    env:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
  
